apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: fluxcd-source-controller.community.tanzu.vmware.com.0.21.3
spec:
  refName: fluxcd-source-controller.community.tanzu.vmware.com
  version: 0.21.3
  releasedAt: "2022-02-07T11:14:08Z"
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tce/fluxcd-source-controller-bundle@sha256:549a2ccd391fd444f3f05e1b95890e8b6bc48b5959548d5a996a5a6ed6eab5ea
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
          - config/kapp.yml
      deploy:
      - kapp: {}
