apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: fluxcd-source-controller.community.tanzu.vmware.com.0.21.4
spec:
  refName: fluxcd-source-controller.community.tanzu.vmware.com
  version: 0.21.4
  releasedAt: "2022-02-07T11:14:08Z"
  valuesSchema:
    valuesSchema:
      openAPIv3:
        properties:
          namespace:
            type: string
            description: Deployment and service namespace
            default: source-system
          limits_cpu:
            type: string
            description: Set cpu usuage limit
            default: 1000m
          limits_memory:
            type: string
            description: Set memory usuage limit
            default: 1Gi
          no_proxy:
            type: string
            description: Set domains for which no proxying should be performed
            default: ""
          https_proxy:
            type: string
            description: Set proxy connection information
            default: ""
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tce/fluxcd-source-controller-bundle@sha256:f8fa8851c9fa21c4749ef6a1d3b440e109c218c27e2268d1708a0577c52606fb
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
          - config/kapp.yml
      deploy:
      - kapp: {}
